### ISSUE TITLE
Renewing Puppet Forge Approved Status

### ISSUE THREAD

**Issue by eimlav** [hercules-team/augeasproviders_base#4]
Hey hercules-team,

Here at puppetlabs, we are currently going through all of our Approved modules on the Puppet Forge. We have some feedback for your module if you would be interested in retaining the approved status. If you are keen on keeping your approved status please ensure you respond as soon as you possibly can.

Many Thanks
The Puppet Approvals Committee

**Comment by raphink** [comment]
@eimlav 	Sure, what is the feedback that needs to be addressed?

**Comment by raphink** [comment]
Thanks for the info @eimlav , I'll try to have a look soon.

**Comment by eimlav** [comment]
Closing the issue as it has now been resolved. Thanks for your help!
